from pathlib import Path

p = Path('mercari_market.py')
s = p.read_text(encoding='utf-8')

# Capture the JSON search response generated by Mercari's own web client.
needle = '''    page.goto(url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT_MS)\n    page.wait_for_timeout(WAIT_AFTER_LOAD_MS)\n'''
replacement = '''    api_responses = []\n\n    def capture_response(response):\n        if "api.mercari.jp/v2/entities:search" in response.url:\n            api_responses.append(response)\n\n    page.on("response", capture_response)\n    page.goto(url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT_MS)\n    page.wait_for_timeout(WAIT_AFTER_LOAD_MS)\n'''
if needle in s and 'api_responses = []' not in s:
    s = s.replace(needle, replacement, 1)

# Add a structured API parser just before browser_lookup.
marker = '\ndef browser_lookup(page, query, debug=False):\n'
helper = r'''

def mercari_api_rows(payload):
    rows = []
    if not isinstance(payload, dict):
        return rows
    for item in payload.get("items", []):
        if not isinstance(item, dict):
            continue
        if item.get("status") != "ITEM_STATUS_SOLD_OUT":
            continue
        if item.get("itemType") != "ITEM_TYPE_MERCARI":
            continue
        if item.get("auction"):
            continue
        raw_price = item.get("price")
        try:
            price = int(float(raw_price))
        except (TypeError, ValueError):
            continue
        if not (MIN_PRICE <= price <= MAX_PRICE):
            continue
        item_id = str(item.get("id") or "").strip()
        if not item_id:
            continue
        rows.append({
            "url": f"https://jp.mercari.com/item/{item_id}",
            "title": normalize(item.get("name") or item.get("title") or ""),
            "price": price,
            "auction": False,
            "sold": True,
            "price_source": "search_api_jpy",
        })
    return rows
'''
if marker in s and 'def mercari_api_rows(payload):' not in s:
    s = s.replace(marker, helper + marker, 1)

# After scrolling, convert the captured API response into canonical JPY rows.
needle2 = '''    page.evaluate("window.scrollTo(0, document.body.scrollHeight)")\n    page.wait_for_timeout(WAIT_AFTER_SCROLL_MS)\n\n    dom_items = collect_dom_items(page)\n'''
replacement2 = '''    page.evaluate("window.scrollTo(0, document.body.scrollHeight)")\n    page.wait_for_timeout(WAIT_AFTER_SCROLL_MS)\n\n    api_rows = []\n    if api_responses:\n        for response in reversed(api_responses):\n            try:\n                api_rows = mercari_api_rows(response.json())\n            except Exception:\n                continue\n            if api_rows:\n                break\n    print("MERCARI_API_SOLD_JPY_ROWS=", len(api_rows))\n\n    dom_items = collect_dom_items(page)\n'''
if needle2 in s and 'MERCARI_API_SOLD_JPY_ROWS=' not in s:
    s = s.replace(needle2, replacement2, 1)

old_block = '''    # First choice: prices directly from sold-result cards.\n    card_rows = []\n    for href, text in candidates[:MAX_CARD_ITEMS]:\n        card_prices = money_values(text)\n        if not card_prices:\n            continue\n        card_rows.append({\n            "url": href,\n            "title": text[:500],\n            "price": card_prices[0],\n            "auction": False,\n            "sold": True,\n            "price_source": "search_card",\n        })\n'''
new_block = '''    # First choice: canonical JPY prices from Mercari's own search API.\n    # The DOM is currency-converted on GitHub's US runner, so DOM prices are not trusted.\n    card_rows = api_rows[:MAX_CARD_ITEMS]\n\n    # Fallback: JPY prices visible directly in the sold-result cards.\n    if not card_rows:\n        for href, text in candidates[:MAX_CARD_ITEMS]:\n            card_prices = money_values(text)\n            if not card_prices:\n                continue\n            card_rows.append({\n                "url": href,\n                "title": text[:500],\n                "price": card_prices[0],\n                "auction": False,\n                "sold": True,\n                "price_source": "search_card",\n            })\n'''
if old_block in s:
    s = s.replace(old_block, new_block, 1)

s = s.replace('''        "price_source": "search_card" if card_rows else ("detail_page_fallback" if rows else None),\n''', '''        "price_source": (card_rows[0].get("price_source") if card_rows else ("detail_page_fallback" if rows else None)),\n''', 1)

p.write_text(s, encoding='utf-8')
print('patched mercari_market.py to use Mercari API JPY sold prices')
